# travis build for k3b-geoHelper
language: android
android:
  components:
    - build-tools-22.0.1
    - android-19
    - add-on
    - extra

script:
  - gradle check assemble reports

after_success:
  - bash <(curl -s https://codecov.io/bash)
  
